# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Live Online Tutoring for Connecticut
email: eric@hilhorst.us
description: > # this means to ignore newlines until "baseurl:"
  This service is meant to help students succeed in their academics
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.simsburytutoringservice.com/" # the base hostname & protocol for your site
twitter_username: We have no twitter yet
github_username:  e12real and pepe454

# Build settings
markdown: kramdown
