baseURL = 'https://deepfriedcode.blog/'
languageCode = 'en-us'
title = 'Deep Fried Code'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
  [[menus.main]]
    name = 'Tag'
    pageRef = '/tags'
    weight = 40
